[package]
name = "wgpu-ffx"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
description = "AMD FidelityFX FSR 3 Upscaler for wgpu"
readme = "../README.md"

[dependencies]
bitflags.workspace = true
bytemuck = { workspace = true, features = ["derive"] }
half = { workspace = true, features = ["bytemuck"] }
thiserror.workspace = true
wgpu = { workspace = true, features = ["spirv", "wgsl"] }
wgpu-ffx-shaders-spv.workspace = true

pollster.workspace = true

[dev-dependencies]
wgpu = { workspace = true, features = ["vulkan", "metal", "dx12"] }
