[base]
FFX_GPU = 1
FFX_GLSL = 1

FFX_FSR3UPSCALER_OPTION_UPSAMPLE_SAMPLERS_USE_DATA_HALF = 0
FFX_FSR3UPSCALER_OPTION_ACCUMULATE_SAMPLERS_USE_DATA_HALF = 0
FFX_FSR3UPSCALER_OPTION_REPROJECT_SAMPLERS_USE_DATA_HALF = 1
FFX_FSR3UPSCALER_OPTION_POSTPROCESSLOCKSTATUS_SAMPLERS_USE_DATA_HALF = 0
FFX_FSR3UPSCALER_OPTION_UPSAMPLE_USE_LANCZOS_TYPE = 2

[permutations]
FFX_HALF = [0, 1]
FFX_WAVE64 = [0, 1]

# Reproject can use either reference lanczos or LUT
FFX_FSR3UPSCALER_OPTION_REPROJECT_USE_LANCZOS_TYPE = [0, 1]
FFX_FSR3UPSCALER_OPTION_HDR_COLOR_INPUT = [0, 1]
FFX_FSR3UPSCALER_OPTION_LOW_RESOLUTION_MOTION_VECTORS = [0, 1]
FFX_FSR3UPSCALER_OPTION_JITTERED_MOTION_VECTORS = [0, 1]
FFX_FSR3UPSCALER_OPTION_INVERTED_DEPTH = [0, 1]
FFX_FSR3UPSCALER_OPTION_APPLY_SHARPENING = [0, 1]
