[package]
name = "xtask"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
pico-args = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
rayon = { workspace = true }
indicatif = { workspace = true }
camino = { workspace = true }
log = { workspace = true }
xshell = { workspace = true }
indexmap = { version = "2.11.4", features = ["serde"] }

[lints]
workspace = true
