//! Core-profile SPD pyramids.
//!
//! Baseline WebGPU (`FormatProfile::Core`) has no multi-channel read-write
//! storage, so FFX's single-pass SPD — which reads back a coherent mip — cannot
//! run. Instead the luma and shading-change pyramids are generated by a chain of
//! **write-only** single-level dispatches: each level reads the previous level as
//! a sampled texture and writes the next as a write-only `rgba16float` storage
//! texture. See `docs/texture-formats.md`.
//!
//! The mode difference is hidden behind [`SpdPyramid`]: Tier2/Native keep the
//! single-pass [`FsrPass`], Core uses [`CoreSpdPyramid`], and both expose the
//! same [`SpdPyramid::dispatch`] so the caller (`lib.rs`) is identical for every
//! profile.

use crate::{
    FormatProfile, FrameKind, FsrContextFlags, FsrDispatchInfo,
    pass::{FsrPass, FsrPassKind, ResourceAccess, create_shader_module},
    resources::{AccessType, FsrResourceName, FsrResources, OwnedBindingResource},
};
use wgpu_ffx_shaders_spv::fsr3upscaler::Shaders;

/// Workgroup tile size of the Core downsample / mip0 passes (must match the
/// `local_size_x/y` in the corresponding `*_core_pass.glsl`).
const CORE_TILE: u32 = 8;

/// Which SPD pyramid is being generated. Selects the source-image reduction and,
/// on Core, whether the auto-exposure (final) pass runs.
#[derive(Debug, Clone, Copy)]
pub(crate) enum SpdPyramidKind {
    Luma,
    ShadingChange,
}

impl SpdPyramidKind {
    fn single_pass_kind(self) -> FsrPassKind {
        match self {
            SpdPyramidKind::Luma => FsrPassKind::LumaPyramid,
            SpdPyramidKind::ShadingChange => FsrPassKind::ShadingChangePyramid,
        }
    }
}

/// An SPD pyramid pass, in whichever form the active profile requires.
pub(crate) enum SpdPyramid {
    /// Tier2 / Native: FFX's single-pass SPD (one dispatch).
    Single(FsrPass),
    /// Core: a chain of write-only single-level dispatches.
    Core(CoreSpdPyramid),
}

impl SpdPyramid {
    pub fn new(
        device: &wgpu::Device,
        kind: SpdPyramidKind,
        flags: FsrContextFlags,
        format_profile: FormatProfile,
        shaders: &Shaders,
    ) -> Self {
        match format_profile {
            FormatProfile::Core => {
                SpdPyramid::Core(CoreSpdPyramid::new(device, kind, format_profile, shaders))
            }
            FormatProfile::Tier2 | FormatProfile::Native => SpdPyramid::Single(FsrPass::new(
                device,
                kind.single_pass_kind(),
                flags,
                format_profile,
                shaders,
            )),
        }
    }

    /// Record the pyramid. The single-pass and Core forms compute their own
    /// dispatch dimensions from `render_size`, so the call site is identical for
    /// every profile.
    #[expect(clippy::too_many_arguments)]
    pub fn dispatch(
        &self,
        device: &wgpu::Device,
        pass: &mut wgpu::ComputePass<'_>,
        resources: &FsrResources,
        info: &FsrDispatchInfo,
        flags: FsrContextFlags,
        frame_kind: FrameKind,
        render_size: [u32; 2],
    ) {
        match self {
            SpdPyramid::Single(single) => {
                // FFX's SPD downsamples one 64x64 tile per workgroup.
                const SPD_TILE: u32 = 64;
                single.dispatch(
                    device,
                    pass,
                    resources,
                    info,
                    flags,
                    frame_kind,
                    render_size[0].div_ceil(SPD_TILE),
                    render_size[1].div_ceil(SPD_TILE),
                );
            }
            SpdPyramid::Core(core) => {
                core.dispatch(device, pass, resources, info, frame_kind, render_size)
            }
        }
    }
}

/// A single Core write-only pass: its pipeline, layout, and the ordered binding
/// roles used to build per-dispatch bind groups.
struct CorePass {
    pipeline: wgpu::ComputePipeline,
    bgl: wgpu::BindGroupLayout,
    bindings: Vec<CoreBinding>,
}

/// The role of one binding in a Core pass. Drives both bind-group-layout and
/// per-dispatch bind-group construction so the two cannot drift apart.
#[derive(Debug, Clone, Copy)]
enum CoreBinding {
    /// Sampled texture resolved by name via [`FsrResources::to_view`].
    Sampled(FsrResourceName),
    /// `spd_mips` sampled at the per-dispatch source mip level.
    SpdSource,
    /// `spd_mips` written write-only at the per-dispatch destination mip level.
    SpdDest,
    /// Write-only storage texture resolved by name (e.g. `farthest_depth_mip1`).
    StorageWrite(FsrResourceName),
    /// Read-write storage buffer resolved by name (`frame_info`).
    StorageBuffer(FsrResourceName),
    /// Uniform buffer resolved by name (`constants`).
    Uniform(FsrResourceName),
    /// Per-level source-index uniform, bound at a per-dispatch offset.
    Level,
    /// Sampler resolved by name.
    Sampler(FsrResourceName),
}

impl CoreBinding {
    fn bgl_entry(self, binding: u32, profile: FormatProfile) -> wgpu::BindGroupLayoutEntry {
        match self {
            CoreBinding::Sampled(name) => name.to_bgl_entry(binding, AccessType::Srv, profile),
            CoreBinding::SpdSource => {
                FsrResourceName::SpdMips.to_bgl_entry(binding, AccessType::Srv, profile)
            }
            CoreBinding::SpdDest => {
                storage_write_entry(binding, FsrResourceName::SpdMips.format(profile))
            }
            CoreBinding::StorageWrite(name) => storage_write_entry(binding, name.format(profile)),
            CoreBinding::StorageBuffer(name) => {
                name.to_bgl_entry(binding, AccessType::Uav, profile)
            }
            CoreBinding::Uniform(name) => name.to_bgl_entry(binding, AccessType::Srv, profile),
            CoreBinding::Level => wgpu::BindGroupLayoutEntry {
                binding,
                visibility: wgpu::ShaderStages::COMPUTE,
                ty: wgpu::BindingType::Buffer {
                    ty: wgpu::BufferBindingType::Uniform,
                    has_dynamic_offset: false,
                    min_binding_size: None,
                },
                count: None,
            },
            CoreBinding::Sampler(name) => name.to_bgl_entry(binding, AccessType::Srv, profile),
        }
    }
}

fn storage_write_entry(binding: u32, format: wgpu::TextureFormat) -> wgpu::BindGroupLayoutEntry {
    wgpu::BindGroupLayoutEntry {
        binding,
        visibility: wgpu::ShaderStages::COMPUTE,
        ty: wgpu::BindingType::StorageTexture {
            access: wgpu::StorageTextureAccess::WriteOnly,
            format,
            view_dimension: wgpu::TextureViewDimension::D2,
        },
        count: None,
    }
}

/// A single-mip texture view descriptor, used to bind one level of `spd_mips`.
fn mip_view(mip: u32) -> wgpu::TextureViewDescriptor<'static> {
    wgpu::TextureViewDescriptor {
        aspect: wgpu::TextureAspect::All,
        base_mip_level: mip,
        mip_level_count: Some(1),
        ..Default::default()
    }
}

/// Texel dimensions of SPD mip `mip` (mip 0 = half resolution), floor-halved to
/// match the physical mip chain. Mirrors `SpdMipSize` in the Core GLSL.
fn spd_mip_size(render: [u32; 2], mip: u32) -> [u32; 2] {
    [
        (render[0] >> (mip + 1)).max(1),
        (render[1] >> (mip + 1)).max(1),
    ]
}

/// The mip level at which the chain reaches 1x1 (the deepest level to produce).
fn last_mip_level(render: [u32; 2]) -> u32 {
    let mut level = 0;
    // Bounded by the largest sensible texture; floor halving always converges.
    while spd_mip_size(render, level) != [1, 1] && level < 16 {
        level += 1;
    }
    level
}

pub(crate) struct CoreSpdPyramid {
    kind: SpdPyramidKind,
    mip0: CorePass,
    downsample: CorePass,
    /// Auto-exposure pass; `Luma` only.
    final_pass: Option<CorePass>,
}

impl CoreSpdPyramid {
    fn new(
        device: &wgpu::Device,
        kind: SpdPyramidKind,
        profile: FormatProfile,
        shaders: &Shaders,
    ) -> Self {
        use CoreBinding::*;
        use FsrResourceName::*;

        let downsample = CorePass::new(
            device,
            "FSR3 SPD Downsample (Core)",
            shaders.spd_downsample_core,
            profile,
            vec![
                SpdSource,
                SpdDest,
                Uniform(Constants),
                Level,
                Sampler(SamplerPointClamp),
                Sampler(SamplerLinearClamp),
            ],
        );

        let (mip0, final_pass) = match kind {
            SpdPyramidKind::Luma => {
                let mip0 = CorePass::new(
                    device,
                    "FSR3 Luma Pyramid mip0 (Core)",
                    shaders.luma_pyramid_core_mip0,
                    profile,
                    vec![
                        Sampled(Luma),
                        Sampled(FarthestDepth),
                        SpdDest,
                        StorageWrite(FarthestDepthMip1),
                        Uniform(Constants),
                        Sampler(SamplerPointClamp),
                        Sampler(SamplerLinearClamp),
                    ],
                );
                let final_pass = CorePass::new(
                    device,
                    "FSR3 Luma Pyramid auto-exposure (Core)",
                    shaders.luma_pyramid_core_final,
                    profile,
                    vec![
                        SpdSource,
                        StorageBuffer(FrameInfo),
                        Uniform(Constants),
                        Sampler(SamplerPointClamp),
                        Sampler(SamplerLinearClamp),
                    ],
                );
                (mip0, Some(final_pass))
            }
            SpdPyramidKind::ShadingChange => {
                let mip0 = CorePass::new(
                    device,
                    "FSR3 Shading Change Pyramid mip0 (Core)",
                    shaders.shading_change_pyramid_core_mip0,
                    profile,
                    vec![
                        Sampled(Luma),
                        Sampled(PreviousLuma),
                        Sampled(OutputDilatedMotionVectors),
                        Sampled(InputExposure),
                        SpdDest,
                        Uniform(Constants),
                        Sampler(SamplerPointClamp),
                        Sampler(SamplerLinearClamp),
                    ],
                );
                (mip0, None)
            }
        };

        Self {
            kind,
            mip0,
            downsample,
            final_pass,
        }
    }

    fn dispatch(
        &self,
        device: &wgpu::Device,
        pass: &mut wgpu::ComputePass<'_>,
        resources: &FsrResources,
        info: &FsrDispatchInfo,
        frame_kind: FrameKind,
        render_size: [u32; 2],
    ) {
        let last_level = last_mip_level(render_size);

        // mip0: reduce the source image into SPD mip 0.
        self.mip0.record(
            device,
            pass,
            resources,
            info,
            frame_kind,
            BindParams {
                src_mip: 0,
                dst_mip: 0,
                level_offset: 0,
            },
            dispatch_groups(spd_mip_size(render_size, 0)),
        );

        // Downsample chain. Luma reduces all the way to 1x1 (for the scene-average
        // auto-exposure); shading change only needs mips 0..2 (its consumer samples
        // those three levels).
        let deepest = match self.kind {
            SpdPyramidKind::Luma => last_level,
            SpdPyramidKind::ShadingChange => last_level.min(2),
        };
        for src in 0..deepest {
            let dst = src + 1;
            self.downsample.record(
                device,
                pass,
                resources,
                info,
                frame_kind,
                BindParams {
                    src_mip: src,
                    dst_mip: dst,
                    level_offset: src as u64 * resources.spd_level_slot_size,
                },
                dispatch_groups(spd_mip_size(render_size, dst)),
            );
        }

        // Auto-exposure from the 1x1 level (Luma only).
        if let Some(final_pass) = &self.final_pass {
            final_pass.record(
                device,
                pass,
                resources,
                info,
                frame_kind,
                BindParams {
                    src_mip: last_level,
                    dst_mip: 0,
                    level_offset: 0,
                },
                (1, 1),
            );
        }
    }
}

/// Per-dispatch values that vary while the bind layout stays fixed.
#[derive(Clone, Copy)]
struct BindParams {
    src_mip: u32,
    dst_mip: u32,
    level_offset: u64,
}

impl CorePass {
    fn new(
        device: &wgpu::Device,
        label: &'static str,
        spirv: &'static [u8],
        profile: FormatProfile,
        bindings: Vec<CoreBinding>,
    ) -> Self {
        let bgl_entries: Vec<_> = bindings
            .iter()
            .enumerate()
            .map(|(i, b)| b.bgl_entry(i as u32, profile))
            .collect();

        let bgl = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
            label: Some(&format!("{label} Bind Group Layout")),
            entries: &bgl_entries,
        });

        let pipeline_layout = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some(&format!("{label} Pipeline Layout")),
            bind_group_layouts: &[Some(&bgl)],
            immediate_size: 0,
        });

        let module = create_shader_module(device, label, spirv);

        let pipeline = device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
            label: Some(label),
            layout: Some(&pipeline_layout),
            module: &module,
            entry_point: Some("main"),
            compilation_options: Default::default(),
            cache: None,
        });

        Self {
            pipeline,
            bgl,
            bindings,
        }
    }

    #[expect(clippy::too_many_arguments)]
    fn record(
        &self,
        device: &wgpu::Device,
        pass: &mut wgpu::ComputePass<'_>,
        resources: &FsrResources,
        info: &FsrDispatchInfo,
        frame_kind: FrameKind,
        params: BindParams,
        groups: (u32, u32),
    ) {
        // Resolve every non-`Level` binding to an owned view/buffer/sampler.
        let owned: Vec<Option<OwnedBindingResource>> = self
            .bindings
            .iter()
            .map(|b| {
                let access = match *b {
                    CoreBinding::Level => return None,
                    CoreBinding::Sampled(name) => ResourceAccess {
                        name,
                        access_type: AccessType::Srv,
                        desc: None,
                    },
                    CoreBinding::SpdSource => ResourceAccess {
                        name: FsrResourceName::SpdMips,
                        access_type: AccessType::Srv,
                        desc: Some(mip_view(params.src_mip)),
                    },
                    CoreBinding::SpdDest => ResourceAccess {
                        name: FsrResourceName::SpdMips,
                        access_type: AccessType::Uav,
                        desc: Some(mip_view(params.dst_mip)),
                    },
                    CoreBinding::StorageWrite(name) => ResourceAccess {
                        name,
                        access_type: AccessType::Uav,
                        desc: None,
                    },
                    CoreBinding::StorageBuffer(name) | CoreBinding::Uniform(name) => {
                        ResourceAccess {
                            name,
                            access_type: AccessType::Uav,
                            desc: None,
                        }
                    }
                    CoreBinding::Sampler(name) => ResourceAccess {
                        name,
                        access_type: AccessType::Srv,
                        desc: None,
                    },
                };
                Some(resources.to_view(info, access, frame_kind))
            })
            .collect();

        let entries: Vec<wgpu::BindGroupEntry> = self
            .bindings
            .iter()
            .enumerate()
            .map(|(i, b)| {
                let resource = match b {
                    CoreBinding::Level => wgpu::BindingResource::Buffer(wgpu::BufferBinding {
                        buffer: &resources.spd_level_buffer,
                        offset: params.level_offset,
                        size: wgpu::BufferSize::new(resources.spd_level_slot_size),
                    }),
                    _ => owned[i]
                        .as_ref()
                        .expect("non-Level binding resolved")
                        .into(),
                };
                wgpu::BindGroupEntry {
                    binding: i as u32,
                    resource,
                }
            })
            .collect();

        let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: None,
            layout: &self.bgl,
            entries: &entries,
        });

        pass.set_pipeline(&self.pipeline);
        pass.set_bind_group(0, &bind_group, &[]);
        pass.dispatch_workgroups(groups.0, groups.1, 1);
    }
}

fn dispatch_groups(size: [u32; 2]) -> (u32, u32) {
    (size[0].div_ceil(CORE_TILE), size[1].div_ceil(CORE_TILE))
}
