name: CI

on:
  push:
    branches: [trunk]
  pull_request:

env:
  CARGO_INCREMENTAL: false
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: short
  RUSTFLAGS: "-Dwarnings"
  RUSTDOCFLAGS: "-Dwarnings"
  CI_RUST_VERSION: "1.94"
  CI_RUST_MSRV: "1.92"

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: cwfitzgerald/repo-common/.github/actions/install-rust@trunk
        with:
          version: ${{ env.CI_RUST_VERSION }}
          components: rustfmt

      - run: cargo fmt --all -- --check

  check:
    name: Check (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - uses: cwfitzgerald/repo-common/.github/actions/install-rust@trunk
        with:
          version: ${{ env.CI_RUST_VERSION }}
          components: clippy

      - run: cargo clippy --workspace --all-features --all-targets

      - run: cargo doc --workspace --no-deps

  wasm:
    name: Check WASM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: cwfitzgerald/repo-common/.github/actions/install-rust@trunk
        with:
          version: ${{ env.CI_RUST_VERSION }}
          components: clippy
          targets: wasm32-unknown-unknown

      - run: cargo clippy -p wgpu-ffx --target wasm32-unknown-unknown --features wgpu/webgpu

      - run: cargo doc -p wgpu-ffx --target wasm32-unknown-unknown --features wgpu/webgpu --no-deps

  test:
    name: Test (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [
            ubuntu-latest,
            # macos-latest, Mac support pending
            # windows-latest, Currently requires passthrough
          ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - uses: cwfitzgerald/repo-common/.github/actions/install-rust@trunk
        with:
          version: ${{ env.CI_RUST_VERSION }}

      - name: Install cargo-nextest
        uses: taiki-e/install-action@cargo-nextest

      - name: (Linux) Install Mesa
        if: runner.os == 'Linux'
        uses: ./.github/actions/install-mesa
        with:
          target-dir: target/debug

      - name: (Windows) Install WARP
        if: runner.os == 'Windows'
        uses: ./.github/actions/install-warp
        with:
          target-dir: target/debug

      - run: cargo nextest run --workspace

  doctest:
    name: Doctest (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - uses: cwfitzgerald/repo-common/.github/actions/install-rust@trunk
        with:
          version: ${{ env.CI_RUST_VERSION }}

      - name: (Linux) Install Mesa
        if: runner.os == 'Linux'
        uses: ./.github/actions/install-mesa
        with:
          target-dir: target/debug

      - name: (Windows) Install WARP
        if: runner.os == 'Windows'
        uses: ./.github/actions/install-warp
        with:
          target-dir: target/debug

      - run: cargo test --workspace --doc

  deny:
    name: Deny
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: cwfitzgerald/repo-common/.github/actions/install-rust@trunk
        with:
          version: ${{ env.CI_RUST_VERSION }}

      - uses: taiki-e/install-action@cargo-deny

      - run: cargo deny --all-features check

  msrv:
    name: MSRV
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: ""
      RUSTDOCFLAGS: ""
    steps:
      - uses: actions/checkout@v6

      - uses: cwfitzgerald/repo-common/.github/actions/install-rust@trunk
        with:
          version: ${{ env.CI_RUST_MSRV }}

      - run: cargo check --workspace

      - run: cargo check --workspace --no-default-features
